# This file contains values from Cookiecutter

default_context:
  project_name: "zotero2notion"
  project_description: "Import zotero library to notion database"
  organization: "rujinlong"
  license: "GNU GPL v3.0"
  minimal_python_version: 3.9
  github_name: "rujinlong"
  email: "jinlong.ru@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
